
name: pr-differ
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install draw.io desktop
        run: |
          wget https://github.com/jgraph/drawio-desktop/releases/download/v29.3.6/drawio-amd64-29.3.6.deb
          apt install ./drawio-amd64-29.3.6.deb
